language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386 lib32z1 lib32ncurses5
deploy:
  provider: releases
  api_key: ${GITHUB_OAUTH_TOKEN}
  file:
    - ./target/project-name-1.0.jar
    - ./target/project-name-1.0.exe
  skip_cleanup: true
  on:
    tags: true