language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386 lib32z1 lib32ncurses5